# frozen_string_literal: true

use_frameworks!
platform :ios, '10.0'
target 'AtomicApp' do
  pod 'AtomicProperty', path: '../'

  target 'AtomicProperty_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~>  8.0.5'
  end
end
